import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import axios from 'axios';
import { useEffect, useState } from 'react';

import { selectRandomFromArray } from '@/util';
import CatCard from '@/components/Molecules/CatCard';
import CatDexCard from '@/components/Molecules/CatDexCard';
import CatDex from '@/components/Organisms/CatDex';



export default function Home({ data }) {

  const [cats, setCats] = useState([]);
  const [cardId, setCardID] = useState()
  const [catDex, setCatDex] = useState(false)

  const options = {
    method: 'GET',
    url: 'http://localhost:3000/api/catbreed',
  };


  const getData = async () => {
    const result = await axios.request(options)
    try {
      console.log(result.data)
      setCats(result.data)
      // console.log(cats)
    }
    catch (error) {
      console.log(error)
    }
  }


  useEffect(() => {
    getData()
    // const random = selectRandomFromArray(data)
    // console.log(random)


  }, [])


  return (

    <>
      <Head>
        <title>Cat Game</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <h1>Cat Test</h1>

        <button onClick={() => { setCatDex(!catDex) }}>TESTTEST</button>
        <CatDex catData={cats} catDex={catDex} onExit={() => { setCatDex(!catDex) }}/>



      </main>
    </>
  )
}

// export async function getServerSideProps(context) {
//   let url = "http://localhost:3000/api/catbreed";
//   // if (process.env.VERCEL_URL) {
//   //   url = `https://${process.env.VERCEL_URL}/api/catbreed`;
//   // }
//   const { data } = await axios({
//     method: 'get',
//     url: url,
//   })
//   return {
//     props: { data }, // will be passed to the page component as props
//   }
// }